### PR TITLE
Feature/get tree by sensor

### LINKED ISSUE #213: Implement functions to get a tree by a sensor id
This is needed to check in the frontend if a sensor is already linked to a tree or not.

### PR DESCRIPTION
**Pull request by doriengr**
Close #213 

After merge:
- [ ] Create issue for GetBySensorID tree repo test

### CODE REVIEW

**Review by choffmann — CHANGES_REQUESTED** [review]
There should be a `404 Not Found' status code response when no tree is found for a sensor ID

image

**Review by choffmann — CHANGES_REQUESTED** [review]
The error message should be `404: sensor not found`

image

**Comment by doriengr** [comment]
> The error message should be `404: sensor not found`
> 
> image

I do not think so. You want to get the tree by a sensor id … so on 404 the tree is not found?

**Review by choffmann — APPROVED** [review]
:+1:

**Pull request merged**
