### PR TITLE
test: utilities

### LINKED ISSUE #223: Test utils

### PR DESCRIPTION
**Pull request by choffmann**
Close #223

### CODE REVIEW

**Comment by choffmann** [comment]
@doriengr there is a function `ParseJSONResponse` in `internal/utils/utils.go` which is only used by tests in the handler. Have you implemented this function? I would like to move this function to the utils files for the http handler. Also, I don't know exactly how to test this function, and if it is only used by tests anyway, we don't need to test the test function.

**Comment by doriengr** [comment]
> @doriengr there is a function `ParseJSONResponse` in `internal/utils/utils.go` which is only used by tests in the handler. Have you implemented this function? I would like to move this function to the utils files for the http handler. Also, I don't know exactly how to test this function, and if it is only used by tests anyway, we don't need to test the test function.

Yes, I created it and as far as I remember I only use it in tests. Feel free to do whatever you want with it 👍

**Review by doriengr — APPROVED** [review]
💯

**Comment by choffmann** [comment]
> > @doriengr there is a function `ParseJSONResponse` in `internal/utils/utils.go` which is only used by tests in the handler. Have you implemented this function? I would like to move this function to the utils files for the http handler. Also, I don't know exactly how to test this function, and if it is only used by tests anyway, we don't need to test the test function.
> 
> Yes, I created it and as far as I remember I only use it in tests. Feel free to do whatever you want with it 👍

I wrote a test for this, perhaps it makes sense to use this function outside the tests as well.

**Pull request merged**
